Update Pull Request guidlines in Traefik/ traefik
traefik/contributors-guide pull request #2
Opened 2022-07-14 16:02 UTC by tfny

We have three sources of truth for our contributing docs.  This updates the source in Traefik/traefik to match the source in doc.traefik.io

I have simply copied and pasted the markdown from the approved source to here.  This does include the title and description information which you may want to adjust.

2022-07-14 16:58 UTC, ldez requested changes

2022-07-14 16:58 UTC, ldez commented on pr_guidelines.md
> +---
```suggestion
```

2022-07-18 15:29 UTC, ldez approved these changes

2022-07-19 07:28 UTC, kevinpollet approved these changes

2022-07-19 07:28 UTC, rtribotte approved these changes

2022-07-19 07:30 UTC, merged